# Generated by Django 4.1.2 on 2023-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipCache',
            fields=[
                ('date', models.DateField(auto_created=True, primary_key=True, serialize=False)),
                ('tip', models.TextField()),
            ],
        ),
    ]
