# Generated by Django 4.1.2 on 2023-02-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('tip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TOTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tip')),
            ],
        ),
        migrations.DeleteModel(
            name='TipCache',
        ),
    ]
