# Generated by Django 4.1.2 on 2023-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tip_totd_delete_tipcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='totd',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
