# Generated by Django 4.1.2 on 2023-02-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_totd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='tip',
            new_name='text',
        ),
    ]
