# Generated by Django 4.1.2 on 2023-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Data Provider',
            field=models.TextField(default='house_4'),
        ),
    ]
