# Generated by Django 4.1.2 on 2023-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_data provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Data Provider',
        ),
        migrations.AddField(
            model_name='user',
            name='data_provider',
            field=models.TextField(default='DALE:house_4'),
        ),
    ]
